#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-genesis
Version  : 2.0
Release  : 3
URL      : https://github.com/apache/geronimo-genesis/archive/genesis-2.0.tar.gz
Source0  : https://github.com/apache/geronimo-genesis/archive/genesis-2.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/geronimo/genesis/genesis-default-flava/2.1/genesis-default-flava-2.1.pom
Source2  : https://repo.maven.apache.org/maven2/org/apache/geronimo/genesis/genesis-default-flava/2.2/genesis-default-flava-2.2.pom
Source3  : https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis-default-flava/2.0/genesis-default-flava-2.0.pom
Source4  : https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis-java5-flava/2.0/genesis-java5-flava-2.0.pom
Source5  : https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis-java5-flava/2.1/genesis-java5-flava-2.1.pom
Source6  : https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis-java5-flava/2.2/genesis-java5-flava-2.2.pom
Source7  : https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis/2.0/genesis-2.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-genesis-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-genesis package.
Group: Data

%description data
data components for the mvn-genesis package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-default-flava/2.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-default-flava/2.1/genesis-default-flava-2.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-default-flava/2.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-default-flava/2.2/genesis-default-flava-2.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-default-flava/2.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-default-flava/2.0/genesis-default-flava-2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-java5-flava/2.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-java5-flava/2.0/genesis-java5-flava-2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-java5-flava/2.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-java5-flava/2.1/genesis-java5-flava-2.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-java5-flava/2.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-java5-flava/2.2/genesis-java5-flava-2.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis/2.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis/2.0/genesis-2.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-default-flava/2.0/genesis-default-flava-2.0.pom
/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-default-flava/2.1/genesis-default-flava-2.1.pom
/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-default-flava/2.2/genesis-default-flava-2.2.pom
/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-java5-flava/2.0/genesis-java5-flava-2.0.pom
/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-java5-flava/2.1/genesis-java5-flava-2.1.pom
/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis-java5-flava/2.2/genesis-java5-flava-2.2.pom
/usr/share/java/.m2/repository/org/apache/geronimo/genesis/genesis/2.0/genesis-2.0.pom
